import Container from "@/components/ui/container";
import { getAllPosts } from "@/lib/posts";
import Head from "next/head";
import Link from "next/link";
import Layout from "@/components/layout";
import { getMenusByLang, companyInfo } from "@/lib/posts";

//With locale parameter, we can get the active locale from the router.
//No need to use useRouter() hook.
//locale parameter is coming from getStaticProps function on default.Like params parameter.
export async function getStaticProps({ locale }) {
  const language = locale.toUpperCase();
  const posts = await getAllPosts(language);
  const menu = await getMenusByLang(locale);
  const contactInfo = await companyInfo();

  return {
    props: {
      posts,
      menu,
      contactInfo,
    },
  };
}

export default function Blog({ posts, menu, contactInfo }) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout menuItems={menu} info={contactInfo}>
        <Container>
          <section className="container mx-auto lg:max-w-5xl post-list mt-4">
            <ul>
              {posts.nodes.map((post) => (
                <li key={post.slug} className="grid grid-cols-5 gap-4 mb-4">
                  <div className="col-span-3">
                    <h2 className="py-4">
                      <Link
                        href={`/blog/${post.slug}`}
                        className="text-blue-400 text-2xl hover:text-blue-600"
                      >
                        {post.title}
                      </Link>
                    </h2>
                    <div className="py-4">{post.date}</div>
                    <div
                      className="text-lg"
                      dangerouslySetInnerHTML={{ __html: post.excerpt }}
                    ></div>
                  </div>
                </li>
              ))}
            </ul>
          </section>
        </Container>
      </Layout>
    </>
  );
}
