import Slider from "@/components/slider";
import Blog from "@/components/blog";
import FeaturedProducts from "@/components/featuredProducts";
import { ImageBox, ImageBox2 } from "@/components/imageBox";
import { HeroSection, HeroSection2 } from "@/components/heroSection";
import NewProdcuts from "@/components/newProducts";
import { reqUrl } from "@/config";
import Head from "next/head";

import Layout from "@/components/layout";
export default function Home({ topNavData, slidersData }) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <NewProdcuts />
        <HeroSection />
        <FeaturedProducts />
        <HeroSection2 />
        <ImageBox />
        <Blog />
      </Layout>
    </>
  );
}
